version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    hostname: elasticsearch
    restart: unless-stopped
    environment:
      - cluster.name=docker-cluster
      - node.name=node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.initial_master_nodes=node1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es7net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    container_name: logstash
    hostname: logstash
    restart: always
    volumes:
      - ./logstash/data:/usr/share/logstash/data:rw
      - ./logstash/template:/usr/share/logstash/template:ro
      #- ./logstash/logs:/usr/share/logstash/logs:rw
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "127.0.0.1:5000:5000/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - es7net
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    hostname: kibana
    environment:
      SERVER_NAME: kibana_server
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - es7net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  juypter:
    image: jupyter/base-notebook
    container_name: juypter
    volumes:
      - ./work:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - 8888:8888

networks:
  es7net:
