version: '2'		 version: '2'
 services:		 services:
   elasticsearch:		 elk:
     image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0		 build: . # 要 docker-compose 執行時建置同目錄下的 Dockerfile
     container_name: elasticsearch		 container_name: kao_elk # 幫 Container 命名，之後比較好打指令
     hostname: elasticsearch		 volumes:
     restart: unless-stopped		 - .:/workspace # 將本地資料夾掛在Container的 /workspace 資料夾下 [host:container]
     environment:		 ports:
       - cluster.name=docker-cluster		 - "9200:9200" # 對應本地與 Container 的連接埠
       - node.name=node1		 - "5601:5601"
       - bootstrap.memory_lock=true		 - "5044:5044"
       - "ES_JAVA_OPTS=-Xms384m -Xmx384m"		
       - "cluster.initial_master_nodes=node1"		
     ulimits:		
       memlock:		
         soft: -1		
         hard: -1		
     volumes:		
       - ./esdata:/usr/share/elasticsearch/data		
     ports:		
       - 9200:9200		
     networks:		
       - es7net		

    logstash:		
     image: docker.elastic.co/logstash/logstash-oss:7.2.0		
     container_name: logstash		
     hostname: logstash		
     restart: always		
     volumes:		
       - .$PWD/logstash:/logstash		
       - ./logstash/pipeline:/usr/share/logstash/pipeline:ro		
       - ./logstash/data:/opt/logstash_data		
       - ./logstash/template:/opt/logstash_template		
       - ./logstash/logs:/usr/share/logstash/logs		
     ports:		
       - "127.0.0.1:5000:5000/udp"		
     environment:		
       LS_JAVA_OPTS: "-Xmx256m -Xms256m"		
     networks:		
       - es7net		
     depends_on:		
       - elasticsearch		

    logspout:		
     image: bekt/logspout-logstash		
     container_name: logspout		
     hostname: logspout		
     restart: always		
     environment:		
       ROUTE_URIS: logstash+tcp://logstash:5000		
     depends_on:		
       - logstash		
     volumes:		
       - /var/run/docker.sock:/var/run/docker.sock		
     networks:		
       - es7net		

    kibana:		
     image: docker.elastic.co/kibana/kibana-oss:7.2.0		
     container_name: kibana		
     hostname: kibana		
     environment:		
       SERVER_NAME: kibana_server		
       ELASTICSEARCH_HOSTS: http://elasticsearch:9200		
     networks:		
       - es7net		
     depends_on:		
       - elasticsearch		
     ports:		
       - 5601:5601		

 
  networks:		
   es7net:
