version: '2'
services:
elk:
build: . # 要 docker-compose 執行時建置同目錄下的 Dockerfile
container_name: kao_elk # 幫 Container 命名，之後比較好打指令
volumes:
- .:/workspace # 將本地資料夾掛在Container的 /workspace 資料夾下 [host:container]
ports:
- "9200:9200" # 對應本地與 Container 的連接埠
- "5601:5601"
- "5044:5044"
