{\rtf1\ansi\ansicpg950\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red29\green150\blue242;\red39\green41\blue50;\red159\green236\blue255;
\red242\green245\blue249;}
{\*\expandedcolortbl;;\cssrgb\c10588\c66275\c96078;\cssrgb\c20392\c21569\c25490;\cssrgb\c67843\c93725\c100000;
\cssrgb\c96078\c96863\c98039;}
\paperw11900\paperh16840\margl1440\margr1440\vieww16200\viewh11780\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
version: \cf4 '2.2'\cf5 \
\cf2 services:\
\cf5   \cf5 \cb3 elastic\cf2 \cb3 :\
\cf5     \cf2 image: \cf5 docker.elastic.co/elasticsearch/elasticsearch:7.7.1\
    \cf2 container_name: \cf5 \cb3 elasticsearch\cf5 \cb3 \
    \cf2 environment:\cf5 \
      - bootstrap.memory_lock=true\
      - \cf4 "ES_JAVA_OPTS=-Xms512m -Xmx512m"\cf5 \
    \cf2 ulimits:\
\cf5       \cf2 memlock:\
\cf5         \cf2 soft: \cf5 -1\
        \cf2 hard: \cf5 -1\
    \cf2 volumes:\
\cf5       - data:/usr/share/elasticsearch/data\
    \cf2 ports:\
\cf5       - 9200:9200\
    \cf2 networks:\
\cf5       - elastic\
\
  \
  \cf2 kibana:\
\cf5     \cf2 image: \cf5 docker.elastic.co/kibana/kibana:7.7.1\
    \cf2 container_name: \cf5 kibana\
    \cf2 ports:\
\cf5       - 5601:5601\
    \cf2 environment:\
\cf5       \cf2 ELASTICSEARCH_URL: \cf5 http://\cf5 \cb3 elasticsearch\cf5 \cb3 :9200\
      \cf2 ELASTICSEARCH_HOSTS: \cf5 http://\cf5 \cb3 elasticsearch\cf5 \cb3 :9200\
    \cf2 networks:\
\cf5       - elastic\
\
\cf2 volumes:\
\cf5   \cf2 data:\
\cf5     \cf2 driver: \cf5 local\
\
\cf2 networks:\
\cf5   \cf2 elastic:\
\cf5     \cf2 driver: \cf5 bridge}